// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClArvQ40_mDKRUz3UJqEjdnh6mvHpov_M',
    appId: '1:789827019684:android:1bcd6992b120a735c45731',
    messagingSenderId: '789827019684',
    projectId: 'flutter-589a6',
    storageBucket: 'flutter-589a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvPxKFYHi_0Q96Lhk2t1kMRujT_xCdAE',
    appId: '1:789827019684:ios:b1055796ce253c79c45731',
    messagingSenderId: '789827019684',
    projectId: 'flutter-589a6',
    storageBucket: 'flutter-589a6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvPxKFYHi_0Q96Lhk2t1kMRujT_xCdAE',
    appId: '1:789827019684:ios:b1055796ce253c79c45731',
    messagingSenderId: '789827019684',
    projectId: 'flutter-589a6',
    storageBucket: 'flutter-589a6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
